version: '2.1'
services:

  tomcat:
    image: biggis/tomcat:8.0.36
    hostname: tomcat
    ports:
      - "8080:8080"
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: tomcat
      TOMCAT_ADMIN: biggis
      TOMCAT_ADMIN_PASSWORD: biggis
