version: '2.1'
services:

  tomcat:
    image: biggis/tomcat:8.5.16
    hostname: tomcat
    ports:
      - "9090:9090"
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: tomcat
      TOMCAT_ADMIN: biggis
      TOMCAT_ADMIN_PASSWORD: biggis
